# Generated by Django 5.0.6 on 2024-07-18 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='description',
        ),
        migrations.AddField(
            model_name='data',
            name='pokedex_entry',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='name',
            field=models.CharField(max_length=500),
        ),
    ]
