# Generated by Django 5.0.6 on 2024-07-18 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_data_description_data_pokedex_entry_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pokedex_entry', models.IntegerField(null=True)),
                ('name', models.CharField(max_length=500)),
                ('url', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Data',
        ),
    ]
