# Generated by Django 5.0.6 on 2024-07-17 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_listing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='name',
            name='pokedex_entry',
            field=models.IntegerField(null=True),
        ),
    ]
